export const USER_PREFS = 'USER_PREFS';
export const LOGOUT = 'LOGOUT';

export const EXTRA_DATA = 'EXTRA_DATA';

export const INTERVIEW_TYPE = 'INTERVIEW_TYPE';

export const JOBS_LIST = 'JOBS_LIST';
export const CANDIDATES_LIST = 'CANDIDATES_LIST';

export const COMPANY_SETTINGS = 'COMPANY_SETTINGS';
export const USER_PROFILE = 'USER_PROFILE';

export const actions = {
  PROFILE_IMAGE: 'PROFILE_IMAGE',
  PROFILE_PERSONAL_INFO: 'PROFILE_PERSONAL_INFO',
  PROFILE_SOCIAL_MEDIA: 'PROFILE_SOCIAL_MEDIA',
  PROFILE_STORY: 'PROFILE_STORY',
  PROFILE_SKILLS: 'PROFILE_SKILLS',
  PROFILE_EDUCATION: 'PROFILE_EDUCATION',
  PROFILE_EXPERIENCES: 'PROFILE_EXPERIENCES',
  PROFILE_CERTIFICATES: 'PROFILE_CERTIFICATES',
  PROFILE_LICENSES: 'PROFILE_LICENSES',
  PROFILE_LANGUAGES: 'PROFILE_LANGUAGES',
  PROFILE_CUSTOM_SECTIONS: 'PROFILE_CUSTOM_SECTIONS',
  PROFILE_AWARDS_AND_HONORS: 'PROFILE_AWARDS_AND_HONORS',
  RESUME_VIEW_FLAGS: 'RESUME_VIEW_FLAGS',
};
